name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18' # The Go version to download (if necessary) and use.
          cache: true
      - name: "Install dependencies"
        run: |
          go get .
      - name: "Run tests"
        run: |
          go test -v .
